# Generated by Django 4.1.2 on 2023-05-07 02:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MidFavoritePokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_user', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_user', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pokedex_id', models.ForeignKey(db_column='pokedex_id', on_delete=django.db.models.deletion.CASCADE, to='models_controller.tblpokemon')),
                ('username', models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mid_favorite_pokemon',
            },
        ),
    ]
