# Generated by Django 4.1.2 on 2023-05-07 23:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models_controller', '0002_midfavoritepokemon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='midfavoritepokemon',
            name='username',
            field=models.ForeignKey(db_column='username', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
